#!/bin/bash
# Sweep over GPU utilization
NUM_TASKSETS=5000
HARMONIC_FLAG=0
FILENAME=$1	#gpu_util_sweep_.csv
EPSILON=0.01
CPU_UTIL=0.4
GPU_TASK_FRACTION=0.5
MAX_GPU_SEGMENTS=40
MAX_NUM_TASKS=10
MAX_GPU_FRACTION=$2 #0.3 0.5 0.7 1.0
MODE=0
for gpu_util in {10..120..10}
do
	GPU_UTIL=$(echo "scale = 1; $gpu_util/100" | bc)
	echo $GPU_UTIL
	../src/uniprocessor_exp.out $NUM_TASKSETS $HARMONIC_FLAG $FILENAME $EPSILON $CPU_UTIL $GPU_UTIL $GPU_TASK_FRACTION $MAX_GPU_SEGMENTS $MAX_NUM_TASKS $MAX_GPU_FRACTION $MODE
done
exit 0